CREATE DATABASE QLBHDT
GO
USE QLBHDT
GO


CREATE TABLE NhomHang(
	MaNhom VARCHAR(10) PRIMARY KEY,
	TenNhom NVARCHAR(100) UNIQUE,
	CongDung NVARCHAR(200)
)
GO


CREATE TABLE LoaiHang(
	MaLoai VARCHAR(10) PRIMARY KEY,
	MaNhom VARCHAR(10) FOREIGN KEY REFERENCES NhomHang(MaNhom),
	TenLoai NVARCHAR(100)
)
GO


CREATE TABLE DonViTinh(
	MaDonVi VARCHAR(10) PRIMARY KEY,
	TenDonVi NVARCHAR(100)
)
GO


CREATE TABLE ChatLieu(
	MaChatLieu VARCHAR(10) PRIMARY KEY,
	TenChatLieu NVARCHAR(100)
)
GO


CREATE TABLE NuocSanXuat(
	MaNuocSanXuat  VARCHAR(10) PRIMARY KEY,
	TenNuocSanXuat NVARCHAR(100)
)
GO



CREATE TABLE CaLam(
	MaCa VARCHAR(10) PRIMARY KEY,
	TenCa NVARCHAR(100)
)
GO


CREATE TABLE CongViec(
	MaCongViec VARCHAR(10) PRIMARY KEY,
	TenCongViec  NVARCHAR(100)
)
GO



CREATE TABLE NhanVien(
	MaNhanVien   VARCHAR(10) PRIMARY KEY,
	TenNhanVien NVARCHAR(100),
	GioiTinh NVARCHAR(10) ,
	NgaySinh DATETIME,
	DienThoai NVARCHAR(30),
	DiaChi NVARCHAR(200),
	MaCa VARCHAR(10) FOREIGN KEY REFERENCES CaLam(MaCa),
	MaCongViec VARCHAR(10) FOREIGN KEY REFERENCES CongViec(MaCongViec)
)
GO



CREATE TABLE KhachHang(
	MaKhach VARCHAR(10) PRIMARY KEY,
	TenKhach NVARCHAR(100),
	DienThoai  NVARCHAR(30),
	DiaChi NVARCHAR(200)
)
GO




CREATE TABLE NhaCungCap(
	MaNCC VARCHAR(10) PRIMARY KEY,
	TenNCC NVARCHAR(100),
	DienThoai  NVARCHAR(30),
	DiaChi NVARCHAR(200)
)
GO



CREATE TABLE HoaDonBan(
	SoHDB  VARCHAR(10) PRIMARY KEY,
	MaNhanVien  VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
	NgayBan DATETIME,
	MaKhach  VARCHAR(10) FOREIGN KEY REFERENCES KhachHang(MaKhach),
	TongTien INT
)
GO


CREATE TABLE HoaDonNhap(
	SoHDN VARCHAR(10) PRIMARY KEY,
	MaNhanVien VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(MaNhanVien),
	NgayNhap DATETIME,
	MaNCC  VARCHAR(10) FOREIGN KEY REFERENCES NhaCungCap(MaNCC),
	TongTien INT
)
GO


CREATE TABLE DanhMucHangHoa(
	MaHang VARCHAR(10) PRIMARY KEY,
	TenHang NVARCHAR(100),
	MaNhom VARCHAR(10) FOREIGN KEY REFERENCES NhomHang(MaNhom),
	MaLoai VARCHAR(10) FOREIGN KEY REFERENCES LoaiHang(MaLoai),
	MaDonVi VARCHAR(10) FOREIGN KEY REFERENCES DonViTinh(MaDonVi),
	MaChatLieu VARCHAR(10) FOREIGN KEY REFERENCES ChatLieu (MaChatLieu),
	MaNuocSanXuat VARCHAR(10) FOREIGN KEY REFERENCES NuocSanXuat(MaNuocSanXuat),
	SoLuong INT ,
	DonGiaNhap INT,
	DonGiaBan INT,
	ThoiGianBaoHanh NVARCHAR(30),
	Anh NVARCHAR(100),
	GhiChu NVARCHAR(100)
)
GO


CREATE TABLE ChiTietHoaDonBan(
	SoHDB VARCHAR(10) FOREIGN KEY REFERENCES HoaDonBan(SoHDB),
	MaHang VARCHAR(10) FOREIGN KEY REFERENCES DanhMucHangHoa(MaHang),
	PRIMARY KEY(SoHDB, MaHang),
	SoLuong INT DEFAULT(0),	
	GiamGia INT,
	ThanhTien INT
)
GO


CREATE TABLE ChiTietHoaDonNhap(
	SoHDN VARCHAR(10) FOREIGN KEY REFERENCES HoaDonNhap(SoHDN),
	MaHang VARCHAR(10) FOREIGN KEY REFERENCES DanhMucHangHoa(MaHang),
	PRIMARY KEY(SoHDN, MaHang),
	SoLuong INT DEFAULT(0),
	DonGiaNhap INT,
	GiamGia INT,
	ThanhTien INT
)
GO